Process "/home/david/Projects/rst2pdf_py2/bin/rst2pdf" started on Sat Jun  6 07:24:40 2015

        /home/david/Projects/rst2pdf_py2/bin/rst2pdf --date-invariant
        -v test_image_alignment.txt -o
        /home/david/Projects/rst2pdf_py2/rst2pdf/tests/output/test_image_alignment.pdf


* [INFO] createpdf.py:1572 Importing extension module 'vectorpdf'
* [INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
* [INFO] styles.py:82 Using stylesheets: 
* [INFO] styles.py:110 FontPath:['/home/david/Projects/rst2pdf_py2/rst2pdf/fonts', '.']
* [INFO] styles.py:111 StylePath:['/home/david/Projects/rst2pdf_py2/rst2pdf/styles', '/home/david/.rst2pdf/styles', '.']
* [INFO] languages.py:39 Language 'en_US' not supported by Docutils, using 'en' instead.
* [ERROR] image.py:357 The image (/home/david/Projects/rst2pdf_py2/rst2pdf/tests/input/images/biohazard.png, near line UNKNOWN in file UNKNOWN) is broken or in an unknown format
* [ERROR] image.py:357 The image (/home/david/Projects/rst2pdf_py2/rst2pdf/tests/input/images/biohazard.png, near line UNKNOWN in file UNKNOWN) is broken or in an unknown format
* Traceback (most recent call last):
*   File "/home/david/Projects/rst2pdf_py2/bin/rst2pdf", line 9, in <module>
*     load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/createpdf.py", line 1495, in main
*     compressed=options.compressed)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/createpdf.py", line 561, in createPdf
*     elements = self.gen_elements(self.doctree)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/basenodehandler.py", line 250, in elemdispatch
*     elements = self.getelements(client, node, style)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/basenodehandler.py", line 225, in getelements
*     elements = self.gather_elements(client, node, style)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/basenodehandler.py", line 205, in gather_elements
*     return client.gather_elements(node, style=style)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/createpdf.py", line 390, in gather_elements
*     r.extend(self.gen_elements(n, style=style))
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/basenodehandler.py", line 250, in elemdispatch
*     elements = self.getelements(client, node, style)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/basenodehandler.py", line 225, in getelements
*     elements = self.gather_elements(client, node, style)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/genelements.py", line 188, in gather_elements
*     return [Paragraph(client.gen_pdftext(node), style)]
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/basenodehandler.py", line 280, in textdispatch
*     text = self.get_text(client, node, replaceEnt)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/basenodehandler.py", line 266, in get_text
*     return client.gather_pdftext(node)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/createpdf.py", line 380, in gather_pdftext
*     for n in node.children])
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/basenodehandler.py", line 280, in textdispatch
*     text = self.get_text(client, node, replaceEnt)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/genpdftext.py", line 194, in get_text
*     w, h, kind = MyImage.size_for_node(node, client=client)
*   File "/home/david/Projects/rst2pdf_py2/rst2pdf/image.py", line 358, in size_for_node
*     raise ValueError
* ValueError

Program /home/david/Projects/rst2pdf_py2/bin/rst2pdf exit code: FAIL (1)   elapsed time: 00.2 seconds

File test_image_alignment.pdf not generated
